### ISSUE TITLE
@colossus9 Workflow

### ISSUE THREAD

**Issue by colossus9** [githubschool/colossus9-banana-bread#4]
@colossus9 will choose an image, add a caption, and add both to a file.

- [ ] #24
- [ ] #25
- [ ] #26
- [ ] #27
- [ ] Request a Review
- [ ] Make more changes
- [ ] Get an approval
- [ ] Merge the Pull Request

**Comment by colossus9** [comment]
Related to #6 , see that issue for more context

**Comment by colossus9** [comment]
This issue is fixed! 🎉 😄 👍

**Comment by mattdavis0351** [comment]
@colossus9 Got your ping!  I'm guessing it's for a demo, if not let me know how I can help 😄
